<<<<<<< HEAD
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (1,'Credilogros','6u9khcqirew1tz.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (2,'Red Megatone','7tcqp8f4gf6a7p.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (3,'Tecno Muebles','9afmdc7rnppll.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (4,'Villanova','9kdhtnlylb9hgl.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (5,'Tarjeta Nevada','49cppzw2c5fdw.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (6,'Nippon Motos','af024p1rqcg6o3.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (7,'Shopping La Capital SRL','b8xsosrmtoo57.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (8,'La Madrileña','bw0h477yxtrusu.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (9,'La Marca','d9vkl66riy6fdp.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (10,'Sapac SA','e7xpagif8niya.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (11,'Agalma','esq771wxb0h7cf.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (12,'Banco Nación','gy7151pq2y370l.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (13,'Qida','hu1rul3ucwp8k.gif',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (14,'Otorgar','lg4isiid84eeub.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (15,'Aluminé Muebles','nbmdv9bgqu36xb.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (16,'Credicom','ntv10scbeouv4z.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (17,'BPN','ny4eeenmskfika.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (18,'Garzonio Propiedades','qrw7hhmk1bbi78.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (19,'Roos Propiedades','qwr8tf10gmohlf.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (20,'Transacciones','s3psty3wvq8466.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (21,'Tarjeta Huilen','t3memewcs7pzt.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (22,'Dormilindo','ysyx3addeydxm1.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (23,'Credito Express','zpv839zl7p3ovo.jpg',1,'I', null)
=======
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (1,'Credilogros','6u9khcqirew1tz.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (2,'Red Megatone','7tcqp8f4gf6a7p.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (3,'Tecno Muebles','9afmdc7rnppll.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (4,'Villanova','9kdhtnlylb9hgl.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (5,'Tarjeta Nevada','49cppzw2c5fdw.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (6,'Nippon Motos','af024p1rqcg6o3.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (7,'Shopping La Capital SRL','b8xsosrmtoo57.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (8,'La Madrileña','bw0h477yxtrusu.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (9,'La Marca','d9vkl66riy6fdp.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (10,'Sapac SA','e7xpagif8niya.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (11,'Agalma','esq771wxb0h7cf.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (12,'Banco Nación','gy7151pq2y370l.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (13,'Qida','hu1rul3ucwp8k.gif',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (14,'Otorgar','lg4isiid84eeub.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (15,'Aluminé Muebles','nbmdv9bgqu36xb.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (16,'Credicom','ntv10scbeouv4z.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (17,'BPN','ny4eeenmskfika.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (18,'Garzonio Propiedades','qrw7hhmk1bbi78.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (19,'Roos Propiedades','qwr8tf10gmohlf.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (20,'Transacciones','s3psty3wvq8466.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (21,'Tarjeta Huilen','t3memewcs7pzt.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (22,'Dormilindo','ysyx3addeydxm1.jpg',1,'I', null)
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (23,'Credito Express','zpv839zl7p3ovo.jpg',1,'I', null)
>>>>>>> refs/remotes/origin/mllarin
 Insert Into web_Banners (id,nombre,imagen,activo,columna,link) values (24,'Paginas Amarillas','paginasAmarillas.jpg',1,'D','http://www.paginasdoradas.com')